### PR TITLE
Add unit tests for SCT verification

### LINKED ISSUE #46: Add unit tests for SCT verification
**Description**

Need unit tests for https://github.com/sigstore/sigstore-go/blob/main/pkg/verify/sct.go.

### PR DESCRIPTION
**Pull request by cmurphy**
Fixes https://github.com/sigstore/sigstore-go/issues/46

### CODE REVIEW

**Review by steiza — COMMENTED** [review]
This is great!

Minor: can we remove the TODO on https://github.com/sigstore/sigstore-go/blob/main/pkg/verify/sct.go#L32 about adding unit tests?

While reviewing, I was thinking about if the SCT functionality should live in https://github.com/sigstore/sigstore-go/blob/main/pkg/testing/ca/ca.go or not. But I think it's better as-is, because this way you can easily provide malformed SCTs for testing.

**Review by Hayden-IO — COMMENTED** [review]
Thank you, this looks great! +1 to removing the TODO

**Comment by cmurphy** [comment]
done

**Review by Hayden-IO — APPROVED** [review]

**Review by steiza — APPROVED** [review]
Thanks, nice work!

**Pull request merged**
