### PR TITLE
Add Policy WithKey() for verifing content you know is signed with a key

### PR DESCRIPTION
**Pull request by steiza**
#### Summary

To address #105.

Right now, if you have a bundle signed with a key, your verification policy needs to include `WithoutIdentitiesUnsafe`. This isn't great though because:
- bundles signed with keys aren't inherently unsafe
- there isn't a way to **require** your bundle was signed with a key - a bundle signed with a certificate would pass `WithoutIdentitiesUnsafe`

#### Release Note

* Added `WithKey()` policy option to require a bundle is signed with a key instead of a certificate

#### Documentation

N/A

### CODE REVIEW

**Review by kommendorkapten — DISMISSED** [review]
Awesome!

**Comment by kommendorkapten** [comment]
How about adding a brief overview/example of the steps to verify with a key (creating the trusted material and configuring the policy) to the `docs/verification.md`, that is not covered right now.

**Review by kommendorkapten — APPROVED** [review]
Love it!

**Review by Hayden-IO — COMMENTED** [review]
Late LGTM, thanks!

**Pull request merged**
